[package]
name = "blackout"
version = "1.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11rb = { version = "0.13.0", features = ["randr", "xinerama"] } 
clap = { version = "4.0", features = ["derive"] }
